### PR TITLE
Support Monacoin.

### PR DESCRIPTION
**Pull request by qingfeng**
看到upstream的master已经增加了monacoin的支持，把相关commit用cherry-pick合并了进来

upstream的对应commit:
https://github.com/richardkiss/pycoin/commit/220de355ed160b69cc73d96cd5bdfbdca83eb4f1

@superisaac pls, review

### CODE REVIEW

**Comment by RyanKung** [comment]
wow @gitthanks

**Comment by gitthanks** [comment]
@RyanKung, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by RyanKung** [comment]
@githanks send 10 ENU to @qingfeng

**Comment by RyanKung** [comment]
@gitthanks send 10 ENU to @qingfeng for this great  work

**Comment by gitthanks** [comment]
@RyanKung, you have bonus 10 ENU to @qingfeng.

**Comment by qingfeng** [comment]
new PR: #4

**Comment by gitthanks** [comment]
@RyanKung, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Comment by gitthanks** [comment]
@RyanKung, you are not the member of [gitthanks.com](https://gitthanks.com) for now. Please login using github and deposit with [Bixin Crypto Wallet](https://bixin.im) first.

**Pull request closed without merging**
